# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rails', '~> 7.0'

gem 'packs-rails', path: File.expand_path('../../..', __dir__)

gem 'sprockets-rails'

gem 'sqlite3', '~> 1.4'

gem 'puma', '~> 5.0'

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
end
