source 'https://rubygems.org'

gem 'rails', '~> 8.0'

gem 'packs-rails', path: File.expand_path('../../..', __dir__)

gem 'sqlite3', '~> 2.0'

gem 'puma', '~> 6.0'

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
end
