name: Label issues as "triage"

on:
  issues:
    types:
      - opened
jobs:
  call-workflow-from-shared-config:
    permissions:
      issues: write
    uses: rubyatscale/shared-config/.github/workflows/triage.yml@main
